package flightbooking;
// Generated 13-Nov-2013 10:44:05 by Hibernate Tools 3.6.0



/**
 * Airport generated by hbm2java
 */
public class Airport  implements java.io.Serializable {


     private int id;
     private String name;
     private String city;
     private String country;
     private Double lat;
     private Double lon;
     private Integer alt;
     private String iata;

    public Airport() {
    }

	
    public Airport(int id) {
        this.id = id;
    }
    public Airport(int id, String name, String city, String country, Double lat, Double lon, Integer alt, String iata) {
       this.id = id;
       this.name = name;
       this.city = city;
       this.country = country;
       this.lat = lat;
       this.lon = lon;
       this.alt = alt;
       this.iata = iata;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLon() {
        return this.lon;
    }
    
    public void setLon(Double lon) {
        this.lon = lon;
    }
    public Integer getAlt() {
        return this.alt;
    }
    
    public void setAlt(Integer alt) {
        this.alt = alt;
    }
    public String getIata() {
        return this.iata;
    }
    
    public void setIata(String iata) {
        this.iata = iata;
    }




}


