package flightbooking;
// Generated 13-Nov-2013 10:44:05 by Hibernate Tools 3.6.0



/**
 * Carrental generated by hbm2java
 */
public class Carrental  implements java.io.Serializable {


     private int licenceno;
     private String drivername;
     private Integer modelyear;
     private Integer kilometers;
     private Integer seatsno;
     private Integer payment;

    public Carrental() {
    }

	
    public Carrental(int licenceno) {
        this.licenceno = licenceno;
    }
    public Carrental(int licenceno, String drivername, Integer modelyear, Integer kilometers, Integer seatsno, Integer payment) {
       this.licenceno = licenceno;
       this.drivername = drivername;
       this.modelyear = modelyear;
       this.kilometers = kilometers;
       this.seatsno = seatsno;
       this.payment = payment;
    }
   
    public int getLicenceno() {
        return this.licenceno;
    }
    
    public void setLicenceno(int licenceno) {
        this.licenceno = licenceno;
    }
    public String getDrivername() {
        return this.drivername;
    }
    
    public void setDrivername(String drivername) {
        this.drivername = drivername;
    }
    public Integer getModelyear() {
        return this.modelyear;
    }
    
    public void setModelyear(Integer modelyear) {
        this.modelyear = modelyear;
    }
    public Integer getKilometers() {
        return this.kilometers;
    }
    
    public void setKilometers(Integer kilometers) {
        this.kilometers = kilometers;
    }
    public Integer getSeatsno() {
        return this.seatsno;
    }
    
    public void setSeatsno(Integer seatsno) {
        this.seatsno = seatsno;
    }
    public Integer getPayment() {
        return this.payment;
    }
    
    public void setPayment(Integer payment) {
        this.payment = payment;
    }




}


