package flightbooking;
// Generated 13-Nov-2013 10:44:05 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Traveller generated by hbm2java
 */
public class Traveller  implements java.io.Serializable {


     private int idno;
     private String travellername;
     private String email;
     private Date traveldate;
     private String fromcode;
     private String tocode;
     private Integer price;

    public Traveller() {
    }

	
    public Traveller(int idno) {
        this.idno = idno;
    }
    public Traveller(int idno, String travellername, String email, Date traveldate, String fromcode, String tocode, Integer price) {
       this.idno = idno;
       this.travellername = travellername;
       this.email = email;
       this.traveldate = traveldate;
       this.fromcode = fromcode;
       this.tocode = tocode;
       this.price = price;
    }
   
    public int getIdno() {
        return this.idno;
    }
    
    public void setIdno(int idno) {
        this.idno = idno;
    }
    public String getTravellername() {
        return this.travellername;
    }
    
    public void setTravellername(String travellername) {
        this.travellername = travellername;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getTraveldate() {
        return this.traveldate;
    }
    
    public void setTraveldate(Date traveldate) {
        this.traveldate = traveldate;
    }
    public String getFromcode() {
        return this.fromcode;
    }
    
    public void setFromcode(String fromcode) {
        this.fromcode = fromcode;
    }
    public String getTocode() {
        return this.tocode;
    }
    
    public void setTocode(String tocode) {
        this.tocode = tocode;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


